// <auto-generated />
using System;
using BranchCompliance.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BranchCompliance.Infrastructure.Migrations
{
    [DbContext(typeof(ComplianceDbContext))]
    partial class ComplianceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BranchCompliance.Domain.Assessments.Appeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("assessment_id");

                    b.Property<int>("ChangeVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("change_version");

                    b.Property<string>("Clarification")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("clarification");

                    b.Property<DateTime?>("DecidedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("decided_at_utc");

                    b.Property<string>("DecidedBy")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("decided_by");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("decision");

                    b.Property<string>("DecisionNote")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("decision_note");

                    b.Property<decimal>("OriginalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("original_score");

                    b.Property<Guid>("PeriodCriterionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("period_criterion_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("reason");

                    b.Property<decimal?>("RevisedScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("revised_score");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("submitted_at_utc");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("submitted_by");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Decision");

                    b.HasIndex("WorkspaceId", "PeriodCriterionId");

                    b.HasIndex("WorkspaceId", "AssessmentId", "PeriodCriterionId")
                        .IsUnique();

                    b.ToTable("appeals");
                });

            modelBuilder.Entity("BranchCompliance.Domain.Assessments.BranchAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AssessorId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("assessor_id");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("branch_code");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("char(36)")
                        .HasColumnName("branch_id");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("branch_name");

                    b.Property<string>("BranchUserId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("branch_user_id");

                    b.Property<int>("ChangeVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("change_version");

                    b.Property<string>("FinalRating")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("final_rating");

                    b.Property<decimal?>("FinalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("final_score");

                    b.Property<DateTime?>("FinalizedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("finalized_at_utc");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("char(36)")
                        .HasColumnName("period_id");

                    b.Property<string>("ProvisionalRating")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("provisional_rating");

                    b.Property<decimal?>("ProvisionalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("provisional_score");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("region");

                    b.Property<DateTime?>("ScoredAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("scored_at_utc");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("state");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("submitted_at_utc");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("AssessorId");

                    b.HasIndex("BranchUserId");

                    b.HasIndex("WorkspaceId", "BranchId");

                    b.HasIndex("WorkspaceId", "BranchUserId");

                    b.HasIndex("WorkspaceId", "PeriodId", "BranchId")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "PeriodId", "FinalScore");

                    b.HasIndex("WorkspaceId", "State", "AssessorId");

                    b.ToTable("assessments");
                });

            modelBuilder.Entity("BranchCompliance.Domain.Assessments.BranchResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("answer");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("assessment_id");

                    b.Property<int>("ChangeVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("change_version");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at_utc");

                    b.Property<Guid>("PeriodCriterionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("period_criterion_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "PeriodCriterionId");

                    b.HasIndex("WorkspaceId", "AssessmentId", "PeriodCriterionId")
                        .IsUnique();

                    b.ToTable("responses");
                });

            modelBuilder.Entity("BranchCompliance.Domain.Assessments.CriterionScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("actor_id");

                    b.Property<Guid?>("AppealId")
                        .HasColumnType("char(36)")
                        .HasColumnName("appeal_id");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("assessment_id");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("at_utc");

                    b.Property<int>("ChangeVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("change_version");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("note");

                    b.Property<Guid>("PeriodCriterionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("period_criterion_id");

                    b.Property<int>("Revision")
                        .HasColumnType("int")
                        .HasColumnName("revision");

                    b.Property<decimal>("Value")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("value");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasAlternateKey("WorkspaceId", "Id");

                    b.HasIndex("WorkspaceId", "AppealId");

                    b.HasIndex("WorkspaceId", "PeriodCriterionId");

                    b.HasIndex("WorkspaceId", "AssessmentId", "PeriodCriterionId", "Revision")
                        .IsUnique();

                    b.ToTable("scores");
                });

            modelBuilder.Entity("BranchCompliance.Domain.Assessments.EvidenceFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("AppealId")
                        .HasColumnType("char(36)")
                        .HasColumnName("appeal_id");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("assessment_id");

                    b.Property<int>("ChangeVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("change_version");

                    b.Property<long>("Length")
                        .HasColumnType("bigint")
                        .HasColumnName("length");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("media_type");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("original_name");

                    b.Property<Guid?>("ResponseId")
                        .HasColumnType("char(36)")
                        .HasColumnName("response_id");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("sha256");

                    b.Property<string>("StorageName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("storage_name");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("uploaded_at_utc");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("uploaded_by");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasAlternateKey("WorkspaceId", "Id");

                    b.HasIndex("WorkspaceId", "AppealId");

                    b.HasIndex("WorkspaceId", "AssessmentId");

                    b.HasIndex("WorkspaceId", "ResponseId");

                    b.HasIndex("WorkspaceId", "StorageName")
                        .IsUnique();

                    b.ToTable("evidence_files");
                });

            modelBuilder.Entity("BranchCompliance.Domain.Branches.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("BranchUserId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("branch_user_id");

                    b.Property<int>("ChangeVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("change_version");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("region");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("BranchUserId");

                    b.HasIndex("WorkspaceId", "Code")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "IsActive");

                    b.ToTable("branches");
                });

            modelBuilder.Entity("BranchCompliance.Domain.Periods.AssessmentPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("AppealDeadlineUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("appeal_deadline_utc");

                    b.Property<DateTime>("AssessmentDeadlineUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("assessment_deadline_utc");

                    b.Property<int>("ChangeVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("change_version");

                    b.Property<DateTime>("FinalizationDeadlineUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("finalization_deadline_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<DateTime>("OpensAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("opens_at_utc");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("phase");

                    b.Property<DateTime>("SubmissionDeadlineUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("submission_deadline_utc");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("char(36)")
                        .HasColumnName("template_id");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("template_name");

                    b.Property<int>("TemplateVersion")
                        .HasColumnType("int")
                        .HasColumnName("template_version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Phase");

                    b.HasIndex("WorkspaceId", "TemplateId");

                    b.ToTable("periods");
                });

            modelBuilder.Entity("BranchCompliance.Domain.Periods.PeriodCriterion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("category");

                    b.Property<int>("CategoryOrder")
                        .HasColumnType("int")
                        .HasColumnName("category_order");

                    b.Property<int>("ChangeVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("change_version");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("code");

                    b.Property<bool>("EvidenceRequired")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("evidence_required");

                    b.Property<string>("Guidance")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("guidance");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("char(36)")
                        .HasColumnName("period_id");

                    b.Property<Guid>("SourceCriterionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("source_criterion_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("title");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("weight");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "PeriodId", "Code")
                        .IsUnique();

                    b.ToTable("period_criteria");
                });

            modelBuilder.Entity("BranchCompliance.Domain.Periods.PeriodRatingBand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("ChangeVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("change_version");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("color");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("label");

                    b.Property<decimal>("MinimumInclusive")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("minimum_inclusive");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("char(36)")
                        .HasColumnName("period_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasAlternateKey("WorkspaceId", "Id");

                    b.HasIndex("WorkspaceId", "PeriodId", "MinimumInclusive")
                        .IsUnique();

                    b.ToTable("period_rating_bands");
                });

            modelBuilder.Entity("BranchCompliance.Domain.Templates.AssessmentTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("ChangeVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("change_version");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("family_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("state");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "FamilyId", "Version")
                        .IsUnique();

                    b.ToTable("templates");
                });

            modelBuilder.Entity("BranchCompliance.Domain.Templates.RatingBand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("ChangeVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("change_version");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("color");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("label");

                    b.Property<decimal>("MinimumInclusive")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("minimum_inclusive");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("char(36)")
                        .HasColumnName("template_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasAlternateKey("WorkspaceId", "Id");

                    b.HasIndex("WorkspaceId", "TemplateId", "MinimumInclusive")
                        .IsUnique();

                    b.ToTable("rating_bands");
                });

            modelBuilder.Entity("BranchCompliance.Domain.Templates.TemplateCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("ChangeVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("change_version");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("char(36)")
                        .HasColumnName("template_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "TemplateId", "Name")
                        .IsUnique();

                    b.ToTable("template_categories");
                });

            modelBuilder.Entity("BranchCompliance.Domain.Templates.TemplateCriterion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)")
                        .HasColumnName("category_id");

                    b.Property<int>("ChangeVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("change_version");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("code");

                    b.Property<bool>("EvidenceRequired")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("evidence_required");

                    b.Property<string>("Guidance")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("guidance");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("char(36)")
                        .HasColumnName("template_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("title");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("weight");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasAlternateKey("WorkspaceId", "Id");

                    b.HasIndex("WorkspaceId", "CategoryId");

                    b.HasIndex("WorkspaceId", "TemplateId", "Code")
                        .IsUnique();

                    b.ToTable("template_criteria");
                });

            modelBuilder.Entity("BranchCompliance.Domain.Workspaces.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("action");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("actor_id");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("at_utc");

                    b.Property<int>("ChangeVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("change_version");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("details");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnName("entity_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasAlternateKey("WorkspaceId", "Id");

                    b.HasIndex("WorkspaceId", "AtUtc");

                    b.ToTable("audit_events");
                });

            modelBuilder.Entity("BranchCompliance.Domain.Workspaces.DemoWorkspace", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("workspace_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime>("LastActivityAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_activity_at_utc");

                    b.Property<int>("SeedVersion")
                        .HasColumnType("int")
                        .HasColumnName("seed_version");

                    b.HasKey("WorkspaceId");

                    b.HasIndex("ExpiresAtUtc");

                    b.ToTable("workspaces");
                });

            modelBuilder.Entity("BranchCompliance.Infrastructure.Identity.DemoUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("asp_net_users", (string)null);
                });

            modelBuilder.Entity("BranchCompliance.Infrastructure.Workspaces.WorkspaceRedirect", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("workspace_id");

                    b.Property<Guid>("ReplacementWorkspaceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("replacement_workspace_id");

                    b.Property<DateTime>("RetiredAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("retired_at_utc");

                    b.HasKey("WorkspaceId");

                    b.HasIndex("RetiredAtUtc");

                    b.ToTable("workspace_redirects");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("asp_net_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("asp_net_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("asp_net_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("longtext")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("BranchCompliance.Domain.Assessments.Appeal", b =>
                {
                    b.HasOne("BranchCompliance.Domain.Workspaces.DemoWorkspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BranchCompliance.Domain.Assessments.BranchAssessment", null)
                        .WithMany("Appeals")
                        .HasForeignKey("WorkspaceId", "AssessmentId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BranchCompliance.Domain.Periods.PeriodCriterion", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "PeriodCriterionId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BranchCompliance.Domain.Assessments.BranchAssessment", b =>
                {
                    b.HasOne("BranchCompliance.Infrastructure.Identity.DemoUser", null)
                        .WithMany()
                        .HasForeignKey("AssessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BranchCompliance.Infrastructure.Identity.DemoUser", null)
                        .WithMany()
                        .HasForeignKey("BranchUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BranchCompliance.Domain.Workspaces.DemoWorkspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BranchCompliance.Domain.Branches.Branch", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "BranchId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BranchCompliance.Domain.Periods.AssessmentPeriod", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "PeriodId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BranchCompliance.Domain.Assessments.BranchResponse", b =>
                {
                    b.HasOne("BranchCompliance.Domain.Workspaces.DemoWorkspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BranchCompliance.Domain.Assessments.BranchAssessment", null)
                        .WithMany("Responses")
                        .HasForeignKey("WorkspaceId", "AssessmentId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BranchCompliance.Domain.Periods.PeriodCriterion", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "PeriodCriterionId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BranchCompliance.Domain.Assessments.CriterionScore", b =>
                {
                    b.HasOne("BranchCompliance.Domain.Workspaces.DemoWorkspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BranchCompliance.Domain.Assessments.Appeal", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "AppealId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BranchCompliance.Domain.Assessments.BranchAssessment", null)
                        .WithMany("Scores")
                        .HasForeignKey("WorkspaceId", "AssessmentId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BranchCompliance.Domain.Periods.PeriodCriterion", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "PeriodCriterionId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BranchCompliance.Domain.Assessments.EvidenceFile", b =>
                {
                    b.HasOne("BranchCompliance.Domain.Workspaces.DemoWorkspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BranchCompliance.Domain.Assessments.Appeal", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "AppealId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BranchCompliance.Domain.Assessments.BranchAssessment", null)
                        .WithMany("Evidence")
                        .HasForeignKey("WorkspaceId", "AssessmentId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BranchCompliance.Domain.Assessments.BranchResponse", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "ResponseId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BranchCompliance.Domain.Branches.Branch", b =>
                {
                    b.HasOne("BranchCompliance.Infrastructure.Identity.DemoUser", null)
                        .WithMany()
                        .HasForeignKey("BranchUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BranchCompliance.Domain.Workspaces.DemoWorkspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BranchCompliance.Domain.Periods.AssessmentPeriod", b =>
                {
                    b.HasOne("BranchCompliance.Domain.Workspaces.DemoWorkspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BranchCompliance.Domain.Templates.AssessmentTemplate", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "TemplateId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BranchCompliance.Domain.Periods.PeriodCriterion", b =>
                {
                    b.HasOne("BranchCompliance.Domain.Workspaces.DemoWorkspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BranchCompliance.Domain.Periods.AssessmentPeriod", null)
                        .WithMany("Criteria")
                        .HasForeignKey("WorkspaceId", "PeriodId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BranchCompliance.Domain.Periods.PeriodRatingBand", b =>
                {
                    b.HasOne("BranchCompliance.Domain.Workspaces.DemoWorkspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BranchCompliance.Domain.Periods.AssessmentPeriod", null)
                        .WithMany("Bands")
                        .HasForeignKey("WorkspaceId", "PeriodId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BranchCompliance.Domain.Templates.AssessmentTemplate", b =>
                {
                    b.HasOne("BranchCompliance.Domain.Workspaces.DemoWorkspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BranchCompliance.Domain.Templates.RatingBand", b =>
                {
                    b.HasOne("BranchCompliance.Domain.Workspaces.DemoWorkspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BranchCompliance.Domain.Templates.AssessmentTemplate", null)
                        .WithMany("Bands")
                        .HasForeignKey("WorkspaceId", "TemplateId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BranchCompliance.Domain.Templates.TemplateCategory", b =>
                {
                    b.HasOne("BranchCompliance.Domain.Workspaces.DemoWorkspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BranchCompliance.Domain.Templates.AssessmentTemplate", null)
                        .WithMany("Categories")
                        .HasForeignKey("WorkspaceId", "TemplateId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BranchCompliance.Domain.Templates.TemplateCriterion", b =>
                {
                    b.HasOne("BranchCompliance.Domain.Workspaces.DemoWorkspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BranchCompliance.Domain.Templates.TemplateCategory", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "CategoryId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BranchCompliance.Domain.Templates.AssessmentTemplate", null)
                        .WithMany("Criteria")
                        .HasForeignKey("WorkspaceId", "TemplateId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BranchCompliance.Domain.Workspaces.AuditEvent", b =>
                {
                    b.HasOne("BranchCompliance.Domain.Workspaces.DemoWorkspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BranchCompliance.Infrastructure.Identity.DemoUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BranchCompliance.Infrastructure.Identity.DemoUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BranchCompliance.Infrastructure.Identity.DemoUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BranchCompliance.Infrastructure.Identity.DemoUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BranchCompliance.Domain.Assessments.BranchAssessment", b =>
                {
                    b.Navigation("Appeals");

                    b.Navigation("Evidence");

                    b.Navigation("Responses");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("BranchCompliance.Domain.Periods.AssessmentPeriod", b =>
                {
                    b.Navigation("Bands");

                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("BranchCompliance.Domain.Templates.AssessmentTemplate", b =>
                {
                    b.Navigation("Bands");

                    b.Navigation("Categories");

                    b.Navigation("Criteria");
                });
#pragma warning restore 612, 618
        }
    }
}
