<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <UserSecretsId>branch-compliance-rating-portfolio</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../BranchCompliance.Infrastructure/BranchCompliance.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
  </ItemGroup>
</Project>
